"""added is_active field

Revision ID: bd9ca1f097d5
Revises: ae6558cdd6d1
Create Date: 2020-05-23 23:26:23.349030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9ca1f097d5'
down_revision = 'ae6558cdd6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
